### ISSUE TITLE
Multiple architectures?

### ISSUE THREAD

**Issue by mdawsonuk** [iitggithub/iperf-server#2]
Is there any possibility of compiling for armv7/armhf and aarch64 as well as amd64? Iperf3 is natively available on all of these platforms, without any need for additional versions per architecture.

**Comment by iitggithub** [comment]
Sounds good to me. Haven't tried it myself but i'll investigate it.

**Comment by odidev** [comment]
Hi Team,   

I have been working on building iitgdocker/iperf-server images for both amd64 and arm64 platforms. Successfully build the docker image for both the platform. 

Added GitHub actions for deploying the Docker image for both the platform. 

**Modified Dockerfile:** https://github.com/odidev/iperf-server/commit/947c6c7dfa77daa51150fa145381abf4854959d2 

Do you have any plans for releasing arm64 images?   
It will be very helpful if an arm64 image is available. If interested, I will raise a PR.

**Comment by mdawsonuk** [comment]
> Hi Team,  
> 
> I have been working on building iitgdocker/iperf-server images for both amd64 and arm64 platforms. Successfully build the docker image for both the platform.
> 
> Added GitHub actions for deploying the Docker image for both the platform.
> 
> **Modified Dockerfile:** [odidev@947c6c7](https://github.com/odidev/iperf-server/commit/947c6c7dfa77daa51150fa145381abf4854959d2)
> 
> Do you have any plans for releasing arm64 images?  
> It will be very helpful if an arm64 image is available. If interested, I will raise a PR.

That's good work :) Would you be able to add armv7 support too? My main motivation for this ticket was running the image on a Raspberry Pi 4

**Comment by odidev** [comment]
@mdawsonuk I have added support for armv7 as well using build.

**Updated Commit:** https://github.com/odidev/iperf-server/commit/f0fe5283e2c30172278c52717dd5fdb33980a653
**Docker Image:** https://hub.docker.com/layers/odidev/iperf-server/latest/images/sha256-db52c4733ef16e0972974f0b76a72e26e68f34bdbf2badb1106af400d63329a3?context=repo

@iitggithub Please review and let me know your feedback. If looks good, I will raise PR.

**Comment by mdawsonuk** [comment]
@odidev Could you submit this as a PR?

**Comment by mdawsonuk** [comment]
@iitggithub any chance there can be some movement on this issue?

**Comment by mdawsonuk** [comment]
Switched to `taoyou/iperf3-alpine` image, this supports armv7l and arm64
